version: "3.7"
services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb_fm"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - .docker/data/mongodb:/data/db
#    ports:
#      - 37017:27017
    command: mongod
    logging:
      driver: json-file
      options:
        max-size: "50m"

  redash_server:
    container_name: redash_server_fm
    image: redash/redash
    depends_on:
      - mongodb
      - redis
      - postgres
    env_file: .docker/env/redash
    restart: always
    command: server
    ports:
      - "9121:5000"
    environment:
      REDASH_WEB_WORKERS: 4
    logging:
      driver: json-file
      options:
        max-size: "50m"

  redash_worker:
    container_name: redash_worker_fm
    image: redash/redash:latest
    depends_on:
      - mongodb
      - redis
      - postgres
    env_file: .docker/env/redash
    command: scheduler
    environment:
      QUEUES: "queries,scheduled_queries,celery"
      WORKERS_COUNT: 2
    logging:
      driver: json-file
      options:
        max-size: "50m"

  postgres:
    container_name: postgres_fm
    image: postgres:9.5-alpine
    #    ports:
    #      - "0901:5432"
    env_file: .docker/env/redash
    volumes:
      - .docker/data/redash/postgres-data:/var/lib/postgresql/data
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "50m"

  redis:
    container_name: redis_fm
    image: redis:5.0-alpine
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "50m"
  python:
    container_name: python_fm
    build:
      context: .docker/python
    env_file: .docker/env/python
    command: python -u scheduler.py
    logging:
      driver: json-file
      options:
        max-size: "50m"
    volumes:
      - ./:/usr/src/app

  mongo-express:
    container_name: mongo_express_fm
    image: mongo-express
    env_file: .docker/env/redash
    depends_on:
      - mongodb
    ports:
      - "12327:8081"
    logging:
      driver: json-file
      options:
        max-size: "50m"
